description = "the default config, you should add your own config to override some of these entries"
features_paths = ["nodefeatures/test_1.feat", "nodefeatures/test_2.feat", "nodefeatures/test_3.feat"]
graph_path = "graphs/test.graph"
[accelerator_settings]
agg_buffer_size = 256
gcn_hidden_size = [16, 16]
gcn_layers = 3
input_buffer_size = 256
mem_config_name = "HBM-config.cfg"
running_mode = "Sparse"
# output_buffer_size = 256
[accelerator_settings.aggregator_settings]
dense_cores = 2
dense_width = 2
sparse_cores = 2
sparse_width = 2
[accelerator_settings.mlp_settings]
mlp_sparse_cores = 2
systolic_cols = 2
systolic_rows = 2
[accelerator_settings.sparsifier_settings]
sparsifier_cols = 2
sparsifier_cores = 2
sparsifier_width = 2
